# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-19 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yokohama_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='alert',
            field=models.BooleanField(),
        ),
    ]
